config/routes.rb
AphellionAngela::Application.routes.draw do







  


  root 'users#login'
  resources :dashboards
  resources :users do
    collection do
      post 'login'
      get  'login'
      get  'registration'
      post 'authenticate'
      get  'add_user'
      get  'view_user'
      post 'save_new_user'
    end
  end

  resources :groups do
    collection do
      get 'add_group'
      get 'view_group'
    end
  end

  resources :dashboard do
    collection do
    end
  end


end

app/models/group.rb
class Group
  include ActiveAttr::Model

  attribute :name
  attribute :description
  attribute :code
  attribute :status
  attribute :role

  validates_presence_of :name, :message => I18n.t('groups.name_req')

end

app/models/user.rb
class User
  include ActiveAttr::Model

  attribute :email
  attribute :alias
  attribute :username
  attribute :password
  attribute :confirmed_password
  attribute :terms
  attribute :first_name
  attribute :last_name
  attribute :mobile_num
  attribute :position

  validates_presence_of :email, :message => I18n.t('users.email_req')
  validates_presence_of :alias, :message => I18n.t('users.alias_req')
  validates_presence_of :username, :message => I18n.t('users.username_req')
  validates_presence_of :password, :message => I18n.t('users.password_req')
  validates_presence_of :confirmed_password, :message => I18n.t('users.con_pass_req')
  validates_acceptance_of :terms,:message => I18n.t('users.term_req')

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index

  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def add_group
    @group = Group.new
  end

  def create
    @group = Group.new(group_permitted_params)

    if @group.valid?
      flash[:notice] = t('groups.group_success')
      redirect_to add_group_groups_path
    else
      render add_group_groups_path
    end
  end

  def view_group

  end

  private

  def group_permitted_params
    params.require(:group).permit(:name,:description,:status,:code,:role)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'layouts/login_layout', :only => [:login, :authenticate,:registration,:create,:show]

  def login

  end

  def registration
    @user = User.new
  end

  def create
    @user = User.new(user_permitted_params)
    if @user.valid?
      flash[:notice] = t('users.reg_success')
      redirect_to :action =>'registration'
    else
      render 'registration'
    end
  end

  def save_new_user
    @user = User.new(user_permitted_params)

    if @user.valid?
      flash[:notice] = t('users.reg_success')
      redirect_to :action =>'add_user'
    else
      render 'add_user'
    end

  end

  def authenticate
    if params[:password].size <= 0 && params[:username].size <= 0
      flash[:error] = t('users.login_error')
    else
      flash[:error] = t('users.invalid_login')
    end
    render login_users_path
  end

  def add_user
   @user = User.new
  end

  def view_user

  end

  private

  def user_permitted_params
    params.require(:user).permit(:username,:password,:confirmed_password, :email,:alias,:terms,:first_name,:last_name,:mobile_num)
  end

  def is_a_valid_email?(email)
    # Check the number of '@' signs.
    if email.count("@") > 0 then
      return true
    elsif email =~ /^.*@.*(.com|.org|.net)$/ then
      return true
    else
      return false
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def change_date_ouput date
    return date.strftime('%m/%d/%Y %I:%M:%S %p')
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/index.html.erb
<div class="container-fluid wrapper-left">
  <div class="row">
    <div class="col-lg-12"><h1 class="color-red">Dashboard</h1> <div class="breadcrumbs">Dashboard | Overview</div></div>
  </div>
</div>
<div class="container-fluid wrapper-stretch">
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-12">
        <div class="col-lg-4 border-panel graph cpu">
          <div class="col-lg-12">
            <h3 style="margin-top: 0px; margin-bottom: 10px;">CPU</h3>
          </div>
          <div class="col-lg-12">
            <div id="line_div" style="width: 100%; height: 180px;"></div>
          </div>
        </div>
        <div class="col-lg-4 border-panel graph ram">
          <div class="col-lg-12">
            <h3 style="margin-top: 0px; margin-bottom: 10px;">RAM</h3>
            <h3 style="float: right; margin-top: -35px;">8 GB</h3>
          </div>
          <div class="col-lg-12">
            <div id="bar_div" style="width: 100%; height: 180px;"></div>
          </div>
        </div>
        <div class="col-lg-4 border-panel graph hdd">
          <div class="col-lg-12">
            <h3 style="margin-top: 0px; margin-bottom: 10px;">HDD</h3>
          </div>
          <div class="col-lg-12">
            <div id="pie_div" style="width: 100%; height: 180px;"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="col-lg-6 border-panel graph network">
          <div class="col-lg-12">
            <h3 style="margin-top: 0px;">Network</h3>
          </div>
          <div class="col-lg-3">
            <h3 style="margin-top: 20px; margin-left: 0px; color: #000; font-weight: bold;">10 Mbps</h3><br/>
            <h5 style="margin-top: -15px; margin-left: 0px; color: #000;">Upload</h5>
            <h3 style="margin-top: 15px; margin-left: 0px; color: #000; font-weight: bold;">20 Mbps</h3><br/>
            <h5 style="margin-top: -15px; margin-left: 0px; color: #000;">Download</h5>
          </div>
          <div class="col-lg-9">
            <div id="chart_div" style="width: 100%; height: 180px;"></div>
          </div>
        </div>
        <div class="col-lg-4 border-panel graph monitor_status">
          <div class="col-lg-12">
            <h3 style="margin-top: 0px; margin-bottom: 10px;">Monitoring Status</h3>
          </div>
          <div class="col-lg-12">
            <dl style="width: 70%">
              <dt>CPU</dt>
              <dd><div id="data-one" class="bar" style="width: 60%">60%</div></dd>
              <dt>RAM</dt>
              <dd><div id="data-two" class="bar" style="width: 80%">80%</div></dd>
              <dt>HDD</dt>
              <dd><div id="data-three" class="bar" style="width: 64%">64%</div></dd>
              <dt>LAN</dt>
              <dd><div id="data-four" class="bar" style="width: 97%">97%</div></dd>
            </dl>
          </div>
        </div>
        <div class="col-lg-2 border-panel graph users">
          <div class="col-lg-12">
            <h3 style="margin-top: 0px; margin-bottom: 10px;">Clients</h3>
          </div>
          <div class="col-lg-12">
            <div class="glyphicon glyphicon-user" style="font-size: 5em; margin-left: 27px;"></div><br/><br/>
            <div class="glyphicon glyphicon-phone" style="font-size: 2.4em; margin-left: 1px; padding: 1px 1px;"></div>
            <div class="glyphicon glyphicon-home" style="font-size: 2.4em; padding: 2px 2px;"></div>
            <div class="glyphicon glyphicon-globe" style="font-size: 2.4em; padding: 2px 5px;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- /#page-content-wrapper -->

</div>

app/views/groups/add_group.html.erb
<div class="container-fluid wrapper-left">
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-12"><h1 class="color-red"><%= t('general.group') %></h1> <div class="breadcrumbs"><%= t('general.group') %> | <%= t('groups.creating_grp') %></div></div>
      <div class="col-lg-12 rectangle-box"><div class="align-top-bottom"><%= t('groups.creating_grp') %></div></div>
      <div class="col-lg-12 square-box">
        <% if @group.errors.any? %>
            <div class="col-md-12">
              <div class="alert alert-danger" id="users_error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <div id="error_explanation">
                  <h4><%= t('phrases.saving_error_sfx', error: pluralize(@group.errors.count, t('general.error'))) %>:</h4>
                  <p>&nbsp;</p>
                  <ul>
                    <% @group.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
        <% end %>

        <%- if !flash[:notice].nil? %>
            <div class="col-md-12">
              <div class="alert alert-success" id="users_error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <div id="error_explanation">

                  <p>&nbsp;</p>
                  <ul>
                    <%= flash[:notice] %>
                  </ul>
                </div>
              </div>
            </div>
        <%- end %>

        <%= form_for(@group) do |v| %>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.name') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:name,:class=>"form-control", :placeholder=> t('general.name')) %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.description') %></div>
              <div class="col-lg-7">
                <%= v.text_area(:description, :class => 'form-control' )  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.status') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:status,:class=>"form-control", :placeholder=> t('general.status')) %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.code') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:status,:class=>"form-control", :placeholder=> t('groups.code')) %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.role') %></div>
              <div class="col-lg-7">
                <select name="role" class="form-control">
                </select>
              </div>
            </div>

            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"></div>
              <div class="col-lg-7">
                <input type="submit" value="submit" class="btn btn-green-group">&nbsp;<a href="<%= view_group_groups_path %>" role="button" class="btn btn-black"><%= t('general.back') %></a><!--<input type="submit" value="back" class="btn btn-black">-->
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/view_group.html.erb
<div class="container-fluid wrapper-left">
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-12"><h1 class="color-red"><%= t('general.user_account') %></h1> <div class="breadcrumbs"><%= t('general.user_account') %> | <%= t('general.user_network') %></div></div>
      <div class="col-lg-12 rectangle-box"><div class="align-top-bottom"><%= t('users.list_of_users') %></div></div>
      <div class="col-lg-12 align-left">
        <button class="btn btn-gray"><span class="glyphicon glyphicon-trash"></span></button>&nbsp;<button class="btn btn-gray"><span class="glyphicon glyphicon-refresh"></span></button>

      </div>
      <div class="col-lg-12 no-padding">
        <table class="table table-striped">
          <thead>
          <tr>
            <th><input type="checkbox"/></th>
            <th><%= t('users.username') %></th>
            <th><%= t('users.email_add') %></th>
            <th><%= t('general.created_at') %></th>
            <th><%= t('general.updated_at') %></th>
            <th style="text-align:center;"><%= t('general.action') %></th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><input type="checkbox"/></td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td style="text-align:center;"><button class="btn btn-circle"><span class="glyphicon glyphicon-trash"></span></button>&nbsp;<button class="btn btn-circle"><span class="glyphicon glyphicon-edit"></span></button></td>
          </tr>
          <tr>
            <td><input type="checkbox"/></td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td style="text-align:center;"><button class="btn btn-circle"><span class="glyphicon glyphicon-trash"></span></button>&nbsp;<button class="btn btn-circle"><span class="glyphicon glyphicon-edit"></span></button></td>
          </tr>
          <tr>
            <td><input type="checkbox"/></td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td>asdasd</td>
            <td style="text-align:center;"><button class="btn btn-circle"><span class="glyphicon glyphicon-trash"></span></button>&nbsp;<button class="btn btn-circle"><span class="glyphicon glyphicon-edit"></span></button></td>
          </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="blog-footer">
      <p><%= t('company.aphelion') %> <b class="blog-footer-bold"><%= t('company.corporation') %></b> &copy; <b class="blog-footer-bold"><%= t('company.spectrum') %></b> <%= t('company.2014') %></p>
</div>

app/views/layouts/_header.html.erb
<nav role="navigation" class="navbar navbar-inverse">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">

    <a href="#" id="menu-toggle" onclick="toggle_menu();" class="navbar-brand"> <span class="glyphicon glyphicon-tasks"></span></a><a href="<%= dashboards_path  %>" class=""><div class="navbar-brand-logo"><img src="/assets/spectrum small.png" ></div></a>
  </div>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse">


    <ul class="nav1 navbar-nav navbar-right">
      <li><a href="#">admin</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <img src="/assets/no_image.png" ><br/>
      <h4>admin</h4>
      <h3> <span class="glyphicon glyphicon-th-large"></span> <span class="glyphicon glyphicon-envelope"></span></h3>
    </li>
    <li class="line-separator">
      <a href="<%= dashboards_path %>"><%= t('general.dashboard') %></a>
    </li>
    <li>
      <a href="#" data-toggle="collapse" data-target="#user" data-parent="#sidenav01" class="collapsed">
        <%= t('general.user_account') %> <span class="caret"></span>
      </a>
      <div class="collapse" id="user" style="height: 0px;">
        <ul class="nav nav-list">
          <li><a href="<%= add_user_users_path %>"><%= t('users.add_user') %></a></li>
          <li><a href="<%= view_user_users_path %>"><%= t('general.user_network') %></a></li>
        </ul>
      </div>
    </li>
    <li>
      <a href="#" data-toggle="collapse" data-target="#group" data-parent="#sidenav02" class="collapsed">
        <%= t('general.groups') %> <span class="caret"></span>
      </a>
      <div class="collapse" id="group" style="height: 0px;">
        <ul class="nav nav-list">
          <li><a href="<%= add_group_groups_path %>"><%= t('groups.add_group') %></a></li>
          <li><a href="<%= view_group_groups_path %>"><%= t('general.group_network') %></a></li>
        </ul>
      </div>
    </li>

    <li>
      <a href="#">Settings</a>
    </li>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AphellionAngela</title>
  <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body class="group">
    <div id="wrapper">
      <%= render partial:'layouts/sidebar' %>
      <div id="page-content-wrapper">
        <%= render partial:'layouts/header' %>
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/layouts/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spectrum | Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

</body>
</html>


app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgileSpectrum</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body id="login">

<%= yield %>

<%= render partial:'layouts/footer' %>
</body>
</html>


app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spectrum | Log-in</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div class="blog-footer">
  <p>APHELION <b class="blog-footer-bold">CORPORATION</b> &copy; <b class="blog-footer-bold">SPECTRUM</b> 2014</p>
</div>

</body>
</html>

app/views/users/add_user.html.erb
<div class="container-fluid wrapper-left">
  <%= form_for(@user,:url=> save_new_user_users_path) do |v| %>
      <div class="row">
        <div class="col-lg-12">
          <div class="col-lg-12"><h1 class="color-red"><%= t('general.user_account') %></h1> <div class="breadcrumbs"><%= t('general.user_account') %> | <%= t('users.creating_user') %></div></div>
          <div class="col-lg-12 rectangle-box"><div class="align-top-bottom"><%= t('users.creating_user') %></div></div>
          <div class="col-lg-12 square-box">
            <% if @user.errors.any? %>
                <div class="col-md-12">
                  <div class="alert alert-danger" id="users_error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div id="error_explanation">
                      <h4><%= t('phrases.saving_error_sfx', error: pluralize(@user.errors.count, t('general.error'))) %>:</h4>
                      <p>&nbsp;</p>
                      <ul>
                        <% @user.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
            <% end %>

            <%- if !flash[:notice].nil? %>
                <div class="col-md-12">
                  <div class="alert alert-success" id="users_error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div id="error_explanation">

                      <p>&nbsp;</p>
                      <ul>
                        <%= flash[:notice] %>
                      </ul>
                    </div>
                  </div>
                </div>
            <%- end %>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('users.email_add') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:email,:class=>"form-control", :placeholder=> t('users.email_add'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.comp_name') %></div>
              <div class="col-lg-7">
                <input type="text" class="form-control"  placeholder="<%= t('general.comp_name') %>">
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('users.username') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:username,:class=>"form-control", :placeholder=> t('users.username'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.password') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:password,:class=>"form-control", :placeholder=> t('general.password'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.confirmed_pass') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:confirmed_password,:class=>"form-control", :placeholder=> t('general.re-password'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('users.alias') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:alias,:class=>"form-control", :placeholder=> t('users.alias'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('users.f_name') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:first_name,:class=>"form-control", :placeholder=> t('users.f_name'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('users.l_name') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:last_name,:class=>"form-control", :placeholder=> t('users.l_name'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('users.mobile_num') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:mobile_num,:class=>"form-control", :placeholder=> t('users.mobile_num'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.position') %></div>
              <div class="col-lg-7">
                <%= v.text_field(:position,:class=>"form-control", :placeholder=> t('general.position'))  %>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.role') %></div>
              <div class="col-lg-7">
                <select name="role" class="form-control" >
                </select>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"><%= t('general.gender') %></div>
              <div class="col-lg-7">
                <select name="gender" class="form-control" >
                </select>
              </div>
            </div>
            <div class="col-lg-12 align-bottom">
              <div class="col-lg-3 align-right"></div>
              <div class="col-lg-7">
                <input type="submit" value="submit" class="btn btn-green-group">&nbsp;<a href="<%= view_user_users_path %>" role="button" class="btn btn-black"><%= t('general.back') %></a>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/users/login.html.erb
<% if flash[:error] %>
    <div class="alert alert-danger" id="users_error">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <strong></strong> <%= @error_alert %>
      <div class="notice"><%= flash[:error] %></div>
    </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <!--Logo Spectrum-->
      <div class="col-md-12">
        <img class="logo-image" src="/assets/spectrum-logo-white.png">
        <div class="text-alignment-left">
          <h1><%= t('general.welcome') %></h1>
          <div class="text-alignment-top">
            <h4><%= t('users.log_in_account') %></h4>
          </div>
        </div>
      </div>
      <div class="col-md-12 box">
        <br/>

          <%= form_tag(authenticate_users_path, { :class => 'form col-md-12 center-block',:role=> 'form' })  do %>
              <div class="form-group">
                <input type="text" class="form-control" name="username" id="exampleInputEmail1" placeholder="<%= t('general.enter_email') %>">
              </div>
              <div class="form-group">
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="<%= t('general.password') %>">
              </div>
              <br/>
              <button type="submit" class="btn btn-green"><%= t('general.log_in') %></button>
              <div class="align"><%= t('general.forgot_pass') %> <a href="#"><%= t('general.click_me') %></a></div>
          <% end %>

      </div>
      <div class="col-md-12">
        <h3><%= t('general.dont_hv_acct') %> <a href="<%= registration_users_path %>"><%= t('general.sign_up') %> </a></h3>
      </div>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>


</body>
</html>

app/views/users/registration.html.erb
<% if @user.errors.any? %>
    <div class="col-md-12">
      <div class="alert alert-danger" id="users_error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div id="error_explanation">
          <h4><%= t('phrases.saving_error_sfx', error: pluralize(@user.errors.count, t('general.error'))) %>:</h4>
          <p>&nbsp;</p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
<% end %>

<%- if !flash[:notice].nil? %>
    <div class="col-md-12">
      <div class="alert alert-success" id="users_error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div id="error_explanation">

          <p>&nbsp;</p>
          <ul>
            <%= flash[:notice] %>
          </ul>
        </div>
      </div>
    </div>
<%- end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <!--Logo Spectrum-->
      <div class="col-md-12">
        <img class="logo-image" src="/assets/spectrum-logo-white.png">
        <div class="text-alignment-left">
          <h1><%= t('general.register') %></h1>
          <div class="text-alignment-top">
            <h4><%= t('general.fill_up') %></h4>
          </div>
        </div>
      </div>
      <div class="col-md-12 box">
        <br/>
        <%= form_for(@user) do |v| %>
          <div class="form-group">
            <input type="text" class="form-control"  placeholder="<%= t('general.comp_name') %>">
          </div>
          <div class="form-group">
            <%= v.text_field(:email,:class=>"form-control", :placeholder=> t('users.email_add'))  %>
          </div>
          <div class="form-group">
            <%= v.text_field(:alias,:class=>"form-control", :placeholder=> t('users.alias'))  %>
          </div>
          <div class="form-group">
            <%= v.text_field(:username,:class=>"form-control", :placeholder=> t('users.username'))  %>
          </div>
          <div class="form-group">
            <%= v.text_field(:password,:class=>"form-control", :placeholder=> t('general.password'))  %>
          </div>
          <div class="form-group">
            <%= v.text_field(:confirmed_password,:class=>"form-control", :placeholder=> t('general.re-password'))  %>
          </div>
          <div class="form-group">
            <%= v.check_box :terms %><%= t('general.agree') %><a href="#">&nbsp;<%= t('users.condition') %></a> and <a href="#"><%= t('users.privacy') %></a>.
          </div>
          <div class="form-group">
            <%= v.submit t('users.sign_up'),class: 'btn btn-green'  %>
          </div>

          <div class="form-group">
            <a href="<%= login_users_path %>" role="button" class="btn btn-green"><%= t('general.back') %></a>
          </div>
        <% end %>
        <div class="col-md-12">
          <br/>
        </div>
      </div>

    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>